// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct DrwaIdentityRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for DrwaIdentityRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = DrwaIdentityRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        DrwaIdentityRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct DrwaIdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> DrwaIdentityRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    /// Initializes the contract with the governance address. 
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&governance)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> DrwaIdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    /// Upgrades storage layout version if needed and preserves existing state. 
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> DrwaIdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    /// Registers a new identity for `subject`. 
    ///  
    /// Sets both KYC and AML status to `"pending"` and sets the initial expiry 
    /// round to the current block round plus `DEFAULT_IDENTITY_VALIDITY_ROUNDS`. 
    /// Access is limited to the governance address or the contract owner. 
    /// Reverts if `subject` is the zero address or an identity already exists. 
    pub fn register_identity<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        subject: Arg0,
        legal_name: Arg1,
        jurisdiction_code: Arg2,
        registration_number: Arg3,
        entity_type: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, drwa_common::DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerIdentity")
            .argument(&subject)
            .argument(&legal_name)
            .argument(&jurisdiction_code)
            .argument(&registration_number)
            .argument(&entity_type)
            .original_result()
    }

    /// Registers an identity using only a 32-byte off-chain identity 
    /// commitment instead of raw legal name / registration-number payloads. 
    ///  
    /// This is the forward-safe path for new DRWA deployments. It preserves 
    /// the existing holder-profile sync semantics while leaving historical 
    /// raw-PII records to a separate migration/disclosure process. 
    pub fn register_identity_commitment<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        subject: Arg0,
        identity_ref_hash: Arg1,
        jurisdiction_code: Arg2,
        entity_type: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, drwa_common::DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerIdentityCommitment")
            .argument(&subject)
            .argument(&identity_ref_hash)
            .argument(&jurisdiction_code)
            .argument(&entity_type)
            .original_result()
    }

    /// Updates the compliance fields for an existing identity and syncs the 
    /// holder profile to the native mirror. 
    ///  
    /// Access is limited to the governance address or the contract owner. 
    /// Reverts if the subject is missing, `expiry_round` is in the past 
    /// unless it is `0`, or `expiry_round` exceeds the configured maximum 
    /// validity window. 
    pub fn update_compliance_status<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<u64>,
    >(
        self,
        subject: Arg0,
        kyc_status: Arg1,
        aml_status: Arg2,
        investor_class: Arg3,
        expiry_round: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, drwa_common::DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("updateComplianceStatus")
            .argument(&subject)
            .argument(&kyc_status)
            .argument(&aml_status)
            .argument(&investor_class)
            .argument(&expiry_round)
            .original_result()
    }

    /// Deactivates an existing identity by setting both KYC and AML status to 
    /// `"deactivated"`, incrementing the holder profile version, and syncing 
    /// the change to the native mirror. 
    ///  
    /// This preserves the audit trail (the record is not deleted). 
    /// Access is limited to the governance address or the contract owner. 
    /// Reverts if the identity does not exist or `subject` is the zero address. 
    pub fn deactivate_identity<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        subject: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, drwa_common::DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("deactivateIdentity")
            .argument(&subject)
            .original_result()
    }

    /// GDPR right-to-erasure endpoint. 
    ///  
    /// Zeros all PII fields (legal_name, registration_number, entity_type, 
    /// investor_class) while preserving the address reference and setting 
    /// jurisdiction_code to "ERASED". Both KYC and AML status are set to 
    /// "deactivated" to prevent the erased identity from passing compliance 
    /// checks. The holder profile is synced to the native mirror so the 
    /// enforcement gate sees the deactivated status immediately. 
    ///  
    /// Unlike `deactivateIdentity`, this endpoint is specifically for GDPR 
    /// Article 17 compliance — it removes personal data while maintaining 
    /// the minimum audit trail required by the regulation. 
    ///  
    /// Access is limited to the governance address or the contract owner. 
    /// Reverts if the identity does not exist or `subject` is the zero address. 
    pub fn erase_identity<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        subject: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, drwa_common::DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("eraseIdentity")
            .argument(&subject)
            .original_result()
    }

    /// Maps a holder address to its identity record. 
    pub fn identity<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        subject: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, IdentityRecord<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getIdentity")
            .argument(&subject)
            .original_result()
    }

    /// Maps a holder address to its privacy-preserving identity commitment. 
    pub fn identity_privacy_commitment<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        subject: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, IdentityPrivacyCommitment<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getIdentityPrivacyCommitment")
            .argument(&subject)
            .original_result()
    }

    /// Updates the identity validity configuration. 
    ///  
    /// Access is limited to the governance address or the contract owner. 
    /// Reverts if `default_rounds` is zero, `max_rounds` is less than 
    /// `default_rounds`, or `max_rounds` exceeds the hard cap of 1,000,000. 
    pub fn set_validity_config<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        default_rounds: Arg0,
        max_rounds: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setValidityConfig")
            .argument(&default_rounds)
            .argument(&max_rounds)
            .original_result()
    }

    /// Storage layout version for forward-compatible upgrades. 
    pub fn storage_version(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u32> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getStorageVersion")
            .original_result()
    }

    /// Proposes a new governance address and starts the acceptance window. 
    pub fn set_governance<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setGovernance")
            .argument(&governance)
            .original_result()
    }

    /// Accepts a pending governance transfer before the acceptance window 
    /// expires. 
    pub fn accept_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("acceptGovernance")
            .original_result()
    }

    /// Revokes the current governance address, clearing all governance and 
    /// pending governance state. Once governance is configured, only that 
    /// governance address may call this endpoint. 
    pub fn revoke_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("revokeGovernance")
            .original_result()
    }

    /// The active governance address authorized to manage compliance state. 
    pub fn governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGovernance")
            .original_result()
    }

    /// The proposed governance address awaiting acceptance. 
    pub fn get_pending_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, Option<ManagedAddress<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPendingGovernance")
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, ManagedVecItem, Clone, PartialEq, Eq)]
pub struct IdentityRecord<Api>
where
    Api: ManagedTypeApi,
{
    pub subject: ManagedAddress<Api>,
    pub legal_name: ManagedBuffer<Api>,
    pub jurisdiction_code: ManagedBuffer<Api>,
    pub registration_number: ManagedBuffer<Api>,
    pub entity_type: ManagedBuffer<Api>,
    pub kyc_status: ManagedBuffer<Api>,
    pub aml_status: ManagedBuffer<Api>,
    pub investor_class: ManagedBuffer<Api>,
    pub expiry_round: u64,
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, ManagedVecItem, Clone, PartialEq, Eq)]
pub struct IdentityPrivacyCommitment<Api>
where
    Api: ManagedTypeApi,
{
    pub subject: ManagedAddress<Api>,
    pub identity_ref_hash: ManagedBuffer<Api>,
    pub committed_round: u64,
}
